// Generated by CoffeeScript 1.7.1
(function() {
  var mod;

  mod = angular.module('coinpagesApp', []);

  mod.controller('app', [
    '$scope', '$http', 'markets', 'currencies', function($scope, $http, markets, currencies) {
      var query;
      query = $http.get('./data/markets.json');
      query.success(function(data) {
        var set, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = data.length; _i < _len; _i++) {
          set = data[_i];
          _results.push(markets.updateLiveData(set));
        }
        return _results;
      });
      $http.get('https://api.vaultofsatoshi.com/public/ticker?order_currency=BTC&payment_currency=CAD').success(function(res) {
        return $http.get('https://api.vaultofsatoshi.com/public/orderbook?order_currency=BTC&payment_currency=CAD&count=3').success(function(book_res) {
          var market;
          market = {
            symbol: "vosCAD",
            avg: Number(res.data.closing_price.value),
            bid: Number(book_res.data.bids[0].price.value),
            ask: Number(book_res.data.asks[0].price.value),
            volume: Number(res.data.units_traded.value)
          };
          return markets.updateLiveData(market);
        });
      });
      $scope.currencies = currencies;
      $scope.state = {
        activeCurrency: 'USD',
        amountBaseline: 1000
      };
      return $scope.markets = markets.data;
    }
  ]);

}).call(this);
