// Generated by CoffeeScript 1.7.1
(function() {
  var mod;

  mod = angular.module('coinpagesApp');

  mod.service('currencies', function() {
    var currencyPairs;
    return currencyPairs = {
      'USD': {
        'CAD': 1.123,
        'CNY': 6.203,
        'EUR': 0.726,
        'USD': 1
      },
      'EUR': {
        'CAD': 1.548,
        'CNY': 8.541,
        'EUR': 1,
        'USD': 1.379
      },
      'CAD': {
        'CAD': 1,
        'CNY': 5.517,
        'EUR': 0.644,
        'USD': 0.889
      }
    };
  });

  mod.filter('currencyConvert', [
    'currencies', function(currencies) {
      return function(amount, currencyFrom, currencyTo) {
        if (amount && currencyFrom && currencyTo) {
          return amount * currencies[currencyFrom][currencyTo];
        } else {
          return "" + amount + " and " + currencyFrom + " and " + currencyTo;
        }
      };
    }
  ]);

}).call(this);
